package main.easy;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 */

public class FindDifference {
    /**
     * Runtime: 3 ms, faster than 99.05% of Java online submissions for Find the Difference.
     * Memory Usage: 26.6 MB, less than 24.85% of Java online submissions for Find the Difference.
     *
     */
    public static char findTheDifference(String s, String t) {

        char[] char_s = s.toCharArray();
        char[] char_t = t.toCharArray();

        int[] asciiTable = new int[26];
        for (char element : char_t)
            asciiTable[element - 'a']++;

        for (char element : char_s)
            asciiTable[element - 'a']--;

        for (int index = 0; index < 26; index++) {
            if (asciiTable[index] != 0)
                return (char) (index + 'a');
        }
        return 'a';

    }

    public static void main(String[] args) {
        char ret = findTheDifference("abcd", "abcde");
        System.out.println(ret); //e

    }

}
